INSERT INTO m_code (code_name, is_system_defined) VALUES ('Salutation', 1);
INSERT INTO m_code (code_name, is_system_defined) VALUES ('Marital Status', 1);
INSERT INTO m_code (code_name, is_system_defined) VALUES ('Profession', 1);
INSERT INTO m_code (code_name, is_system_defined) VALUES ('Educational Qualification', 1);
INSERT INTO m_code (code_name, is_system_defined) VALUES ('Annual Income', 1);
INSERT INTO m_code (code_name, is_system_defined) VALUES ('Land Holdings', 1);
INSERT INTO m_code (code_name, is_system_defined) VALUES ('House Type', 1);
INSERT INTO m_code (code_name, is_system_defined) VALUES ('State', 1);
INSERT INTO m_code (code_name, is_system_defined) VALUES ('District', 1);
INSERT INTO m_code (code_name, is_system_defined) VALUES ('Country', 1);
INSERT INTO m_code (code_name, is_system_defined) VALUES ('Identity Proof', 1);
INSERT INTO m_code (code_name, is_system_defined) VALUES ('Address Proof', 1);
INSERT INTO m_code (code_name, is_system_defined) VALUES ('Family RelationShip', 1);
INSERT INTO m_code (code_name, is_system_defined) VALUES ('Family Occupation', 1);
INSERT INTO m_code (code_name, is_system_defined) VALUES ('Client Financial Activity Occupations', 1);
INSERT INTO m_code (code_name, is_system_defined) VALUES ('External Loan Status', 1);
INSERT INTO m_code (code_name, is_system_defined) VALUES ('Address Type', 1);
INSERT INTO m_code (code_name, is_system_defined) VALUES ('Present Loan Source Types', 1);
INSERT INTO m_code (code_name, is_system_defined) VALUES ('Present Loan Purpose Types', 1);
INSERT INTO m_code (code_name, is_system_defined) VALUES ('Spouse/Parent RelationShip', 1);