CREATE TABLE `ct_client_ext` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`client_id` BIGINT(20) NOT NULL,
	`salutation_cv_id` INT(11) NULL DEFAULT NULL,
	`marital_status_cv_id` INT(11) NULL DEFAULT NULL,
	`profession_cv_id` INT(11) NULL DEFAULT NULL,
	`profession_others` VARCHAR(100) NULL DEFAULT NULL,
	`educational_qualification_cv_id` INT(11) NULL DEFAULT NULL,
	`annual_income_cv_id` INT(11) NULL DEFAULT NULL,
	`landholding_cv_id` INT(11) NULL DEFAULT NULL,
	`house_type_cv_id` INT(11) NULL DEFAULT NULL,
	`aadhaar_no` VARCHAR(100) NULL DEFAULT NULL,
	`pan_no` VARCHAR(100) NULL DEFAULT NULL,
	`pan_form_cv_id` INT(11) NULL DEFAULT NULL,
	`nrega_no` VARCHAR(100) NULL DEFAULT NULL,
	`sp_firstname` VARCHAR(100) NULL DEFAULT NULL,
	`sp_middlename` VARCHAR(100) NULL DEFAULT NULL,
	`sp_lastname` VARCHAR(100) NULL DEFAULT NULL,
	`father_spouse_inda` INT(11) NULL DEFAULT NULL,
	`external_Id2` VARCHAR(100) NULL DEFAULT NULL,
	PRIMARY KEY (`id`),
	UNIQUE INDEX `client_id_UNIQUE` (`client_id`),
	INDEX `fk_n_client_ext_salutation_cv_id` (`salutation_cv_id`),
	INDEX `fk_n_client_ext_marital_status_cv_id` (`marital_status_cv_id`),
	INDEX `fk_n_client_ext_profession_cv_id` (`profession_cv_id`),
	INDEX `fk_n_client_ext_eq_cv_id` (`educational_qualification_cv_id`),
	INDEX `fk_n_client_ext_annual_income_cv_id` (`annual_income_cv_id`),
	INDEX `fk_n_client_ext_landholding_cv_id` (`landholding_cv_id`),
	INDEX `fk_n_client_ext_house_type_cv_id` (`house_type_cv_id`),
	INDEX `fk_n_client_ext_pan_form_cv_id` (`pan_form_cv_id`),
	CONSTRAINT `fk_n_client_ext_annual_income_cv_id` FOREIGN KEY (`annual_income_cv_id`) REFERENCES `m_code_value` (`id`),
	CONSTRAINT `fk_n_client_ext_client_id_m_client` FOREIGN KEY (`client_id`) REFERENCES `m_client` (`id`),
	CONSTRAINT `fk_n_client_ext_eq_cv_id` FOREIGN KEY (`educational_qualification_cv_id`) REFERENCES `m_code_value` (`id`),
	CONSTRAINT `fk_n_client_ext_house_type_cv_id` FOREIGN KEY (`house_type_cv_id`) REFERENCES `m_code_value` (`id`),
	CONSTRAINT `fk_n_client_ext_landholding_cv_id` FOREIGN KEY (`landholding_cv_id`) REFERENCES `m_code_value` (`id`),
	CONSTRAINT `fk_n_client_ext_marital_status_cv_id` FOREIGN KEY (`marital_status_cv_id`) REFERENCES `m_code_value` (`id`),
	CONSTRAINT `fk_n_client_ext_pan_form_cv_id` FOREIGN KEY (`pan_form_cv_id`) REFERENCES `m_code_value` (`id`),
	CONSTRAINT `fk_n_client_ext_profession_cv_id` FOREIGN KEY (`profession_cv_id`) REFERENCES `m_code_value` (`id`),
	CONSTRAINT `fk_n_client_ext_salutation_cv_id` FOREIGN KEY (`salutation_cv_id`) REFERENCES `m_code_value` (`id`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;